/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CommercialMovingRouteImport } from './routes/commercial-moving'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MovingServicesRouteImport } from './routes/moving-services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ResidentialMovingRouteImport } from './routes/residential-moving'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAreasRouteImport } from './routes/admin.areas'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialMovingRoute = CommercialMovingRouteImport.update({
  id: '/commercial-moving',
  path: '/commercial-moving',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingServicesRoute = MovingServicesRouteImport.update({
  id: '/moving-services',
  path: '/moving-services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialMovingRoute = ResidentialMovingRouteImport.update({
  id: '/residential-moving',
  path: '/residential-moving',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAreasRoute = AdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/commercial-moving': typeof CommercialMovingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/moving-services': typeof MovingServicesRoute
  '/quote': typeof QuoteRoute
  '/residential-moving': typeof ResidentialMovingRoute
  '/service-areas': typeof ServiceAreasRoute
  '/track': typeof TrackRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/commercial-moving': typeof CommercialMovingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/moving-services': typeof MovingServicesRoute
  '/quote': typeof QuoteRoute
  '/residential-moving': typeof ResidentialMovingRoute
  '/service-areas': typeof ServiceAreasRoute
  '/track': typeof TrackRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/commercial-moving': typeof CommercialMovingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/moving-services': typeof MovingServicesRoute
  '/quote': typeof QuoteRoute
  '/residential-moving': typeof ResidentialMovingRoute
  '/service-areas': typeof ServiceAreasRoute
  '/track': typeof TrackRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/commercial-moving'
    | '/contact'
    | '/faq'
    | '/moving-services'
    | '/quote'
    | '/residential-moving'
    | '/service-areas'
    | '/track'
    | '/admin/areas'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/faqs'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipments'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/commercial-moving'
    | '/contact'
    | '/faq'
    | '/moving-services'
    | '/quote'
    | '/residential-moving'
    | '/service-areas'
    | '/track'
    | '/admin/areas'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/faqs'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipments'
    | '/services/$slug'
    | '/admin'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/commercial-moving'
    | '/contact'
    | '/faq'
    | '/moving-services'
    | '/quote'
    | '/residential-moving'
    | '/service-areas'
    | '/track'
    | '/admin/areas'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/faqs'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipments'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  CommercialMovingRoute: typeof CommercialMovingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MovingServicesRoute: typeof MovingServicesRoute
  QuoteRoute: typeof QuoteRoute
  ResidentialMovingRoute: typeof ResidentialMovingRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  TrackRoute: typeof TrackRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-moving': {
      id: '/commercial-moving'
      path: '/commercial-moving'
      fullPath: '/commercial-moving'
      preLoaderRoute: typeof CommercialMovingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-services': {
      id: '/moving-services'
      path: '/moving-services'
      fullPath: '/moving-services'
      preLoaderRoute: typeof MovingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-moving': {
      id: '/residential-moving'
      path: '/residential-moving'
      fullPath: '/residential-moving'
      preLoaderRoute: typeof ResidentialMovingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/areas': {
      id: '/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAreasRoute: typeof AdminAreasRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAreasRoute: AdminAreasRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  CommercialMovingRoute: CommercialMovingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MovingServicesRoute: MovingServicesRoute,
  QuoteRoute: QuoteRoute,
  ResidentialMovingRoute: ResidentialMovingRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  TrackRoute: TrackRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
